import os
import configparser


CRYTON_WORKER_CONFIG_PATH = os.getenv('CRYTON_WORKER_CONFIG', '/etc/cryton/config-worker.ini')

DEBUG = True if os.getenv('CRYTON_WORKER_DEBUG') == 'True' else False

MSFRPCD_PASS = os.getenv('CRYTON_WORKER_MSFRPCD_PASS')
MSFRPCD_USERNAME = os.getenv('CRYTON_WORKER_MSFRPCD_USERNAME')
MSFRPCD_PORT = int(os.getenv('CRYTON_WORKER_MSFRPCD_PORT'))
MSFRPCD_SSL = os.getenv('CRYTON_WORKER_MSFRPCD_SSL') == 'True'

MODULES_DIR = os.getenv('CRYTON_WORKER_MODULES_DIR')

RABBIT_USERNAME = os.getenv('CRYTON_WORKER_RABBIT_USERNAME')
RABBIT_PASSWORD = os.getenv('CRYTON_WORKER_RABBIT_PASSWORD')
RABBIT_SRV_ADDR = os.getenv('CRYTON_WORKER_RABBIT_SRV_ADDR')
RABBIT_SRV_PORT = int(os.getenv('CRYTON_WORKER_RABBIT_SRV_PORT'))

RABBIT_WORKER_PREFIX = os.getenv('CRYTON_WORKER_RABBIT_WORKER_PREFIX')
CONSUMER_COUNT = int(os.getenv('CRYTON_WORKER_CONSUMER_COUNT'))

config = configparser.ConfigParser(allow_no_value=True)
config.read(CRYTON_WORKER_CONFIG_PATH)

LOG_CONFIG = config.get('LOGGING_CONFIG', 'LOG_CONFIG')
