from os import getenv


MSFRPCD_PASS = getenv("CRYTON_WORKER_MSFRPCD_PASS")
MSFRPCD_USERNAME = getenv("CRYTON_WORKER_MSFRPCD_USERNAME")
MSFRPCD_PORT = int(getenv("CRYTON_WORKER_MSFRPCD_PORT"))
MSFRPCD_SSL = True if getenv("CRYTON_WORKER_MSFRPCD_SSL").lower() == "true" else False

RABBIT_USERNAME = getenv("CRYTON_WORKER_RABBIT_USERNAME")
RABBIT_PASSWORD = getenv("CRYTON_WORKER_RABBIT_PASSWORD")
RABBIT_RHOST = getenv("CRYTON_WORKER_RABBIT_RHOST")
RABBIT_RPORT = int(getenv("CRYTON_WORKER_RABBIT_RPORT"))
RABBIT_WORKER_PREFIX = getenv("CRYTON_WORKER_RABBIT_WORKER_PREFIX")

EMPIRE_RHOST = getenv("CRYTON_WORKER_EMPIRE_RHOST")
EMPIRE_RPORT = getenv("CRYTON_WORKER_EMPIRE_RPORT")
EMPIRE_USERNAME = getenv("CRYTON_WORKER_EMPIRE_USERNAME")
EMPIRE_PASSWORD = getenv("CRYTON_WORKER_EMPIRE_PASSWORD")

MODULES_DIR = getenv("CRYTON_WORKER_MODULES_DIR")
DEBUG = True if getenv("CRYTON_WORKER_DEBUG").lower() == "true" else False
CONSUMER_COUNT = int(getenv("CRYTON_WORKER_CONSUMER_COUNT"))
PROCESSOR_COUNT = int(getenv("CRYTON_WORKER_PROCESSOR_COUNT"))
MAX_RETRIES = int(getenv("CRYTON_WORKER_MAX_RETRIES"))
INSTALL_REQUIREMENTS = True if getenv("CRYTON_WORKER_INSTALL_REQUIREMENTS").lower() == "true" else False
